name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: PULL最新程式碼
        uses: actions/checkout@v3


      - name: SSH 到遠端 VM
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.REMOTE_VM_HOST }}
          username: ${{ secrets.REMOTE_VM_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sh /home/liqingbao/deploy_front.sh